
version: '3.4'

networks:
  splunknet:
    driver: bridge
    attachable: true

volumes:
  log-data:

services:

  splunk:
    networks: [ splunknet ]
    image: splunk/splunk
    environment:
      SPLUNK_LICENSE_URI: Free
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_STANDALONE_URL: splunk
      SPLUNK_HEAVY_FORWARDER_URL: splunk-hf
      SPLUNK_ROLE: splunk_standalone
      SPLUNK_PASSWORD: password
    ports:
      - 80:8000
      - 8089

  splunk-hf:
    networks: [ splunknet ]
    image: splunk/splunk
    command: start
    environment:
      SPLUNK_LICENSE_URI: Free
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_STANDALONE_URL: splunk
      SPLUNK_HEAVY_FORWARDER_URL: splunk-hf
      SPLUNK_ROLE: splunk_heavy_forwarder
      SPLUNK_PASSWORD: password
    ports:
      - 8000
      - 8089
    depends_on:
      - splunk
    volumes:
      - log-data:/var/log:ro
      - ./.splunk/inputs.conf:/opt/splunk/etc/system/local/inputs.conf
      - ./.splunk/props.conf:/opt/splunk/etc/system/local/props.conf

  splunk-practice:
    build: .
    image: hypersonicgoat/splunk-practice
    ports:
    - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - splunk-hf
    volumes:
      - log-data:/app/logs
