
version: '3.4'

networks:
  splunknet:
    driver: bridge
    attachable: true

volumes:
  log-data:

services:

  splunk:
    networks: [ splunknet ]
    image: splunk/splunk
    environment:
      SPLUNK_LICENSE_URI: Free
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_STANDALONE_URL: splunk
      SPLUNK_PASSWORD: password
    ports:
      - 80:8000
      - 8089

  splunk-forward:
    networks: [ splunknet ]
    image: splunk/universalforwarder
    environment:
      SPLUNK_LICENSE_URI: Free
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_STANDALONE_URL: splunk
      SPLUNK_PASSWORD: password
    ports:
      - 8089
    depends_on:
      - splunk
    volumes:
      - log-data:/var/log:ro
      - ./.splunk:/opt/splunkforwarder/etc/system/local

  splunk-practice:
    build: .
    image: hypersonicgoat/splunk-practice
    ports:
    - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - splunk-forward
    volumes:
      - log-data:/app/logs
